CREATE TABLE task
(
    task_id        bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    public_task_id uuid ,
    description    text ,
    status         text
);

CREATE TABLE account
(
    account_id        bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    public_account_id uuid   ,
    email             text   ,
    role              text[]
);

CREATE TABLE task_account
(
    task_id    bigint ,
    account_id bigint
)
